name: Windows Desktop (noVNC)

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: windows-latest
    timeout-minutes: 360  # max 6 saat

    steps:
      - name: Install Chocolatey and noVNC dependencies
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install tigervnc -y
          choco install novnc -y
          choco install python -y
          pip install websockify
          curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -o cloudflared.exe

      - name: Configure VNC Server
        run: |
          mkdir $env:USERPROFILE\.vnc
          $passwd = "test123"
          echo $passwd | vncpasswd -f > $env:USERPROFILE\.vnc\passwd
          icacls $env:USERPROFILE\.vnc\passwd /inheritance:r /grant:r "$env:USERNAME":R

      - name: Start VNC and noVNC
        run: |
          start-process vncserver -ArgumentList ":1 -geometry 1920x1080 -depth 24 -localhost"
          start-process websockify -ArgumentList "6080 localhost:5901"

      - name: Start Cloudflare Tunnel
        run: |
          start-process .\cloudflared.exe -ArgumentList "tunnel --url http://localhost:6080 --no-autoupdate"
          Start-Sleep -Seconds 10
          Get-Content cloudflared.log

      - name: Show Connection Info
        run: |
          echo "## Web Windows Desktop (noVNC)" >> $env:GITHUB_STEP_SUMMARY
          echo "URL: (Cloudflare logundan alın)" >> $env:GITHUB_STEP_SUMMARY
          echo "Password: test123" >> $env:GITHUB_STEP_SUMMARY
          echo "Not: Bu oturum workflow bitene kadar (max 6 saat) açık kalır." >> $env:GITHUB_STEP_SUMMARY

      - name: Keep session alive
        run: Start-Sleep -Seconds 21600
